name: "binding"
shortDesc: "This command interacts with Service Bindings"
command: "start binding"
tree:
  - name: "list"
    shortDesc: "Lists all Service Bindings in a particular namespace"
    command: "start binding list"
  - name: "get"
    shortDesc: "Gets a particular Service Bindings in a particular namespace"
    command: "start binding get"
