name: "broker"
shortDesc: "This command interacts with Cluster Service Brokers"
command: "start broker"
tree:
  - name: "list"
    shortDesc: "Lists all Cluster Service Brokers"
    command: "start broker list"
  - name: "get"
    shortDesc: "Gets a particular Cluster Service Broker"
    command: "start broker get"
