name: "instance"
shortDesc: "This command interacts with Service Instances"
command: "start instance"
tree:
  - name: "list"
    shortDesc: "Lists all Service Instances in a particular namespace"
    command: "start instance list"
  - name: "get"
    shortDesc: "Gets a particular Service Instance in a particular namespace"
    command: "start instance get"
