name: "class"
shortDesc: "This command interacts with Cluster Service Classes"
command: "start class"
tree:
  - name: "list"
    shortDesc: "Lists all Cluster Service Classes"
    command: "start class list"
  - name: "get"
    shortDesc: "Gets a particular Cluster Service Class"
    command: "start class get"
